platform :ios, '9.3'
target 'test' do
  use_frameworks!
  pod 'ViroReact', :path => '../node_modules/react-viro/ios/'
  pod 'ViroKit', :path => '../node_modules/react-viro/ios/dist/ViroRenderer/'
  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'react-native-keep-awake', :path => '../node_modules/react-native-keep-awake'

  pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

end
